_commit: v1.5.1
_src_path: gh:superlinear-ai/substrate
author_email: laurent@superlinear.eu
author_name: Laurent Sorber
project_description: A Python toolkit for Retrieval-Augmented Generation (RAG) with
    SQLite or PostgreSQL.
project_name: raglite
project_type: package
project_url: https://github.com/superlinear-ai/raglite
python_version: '3.10'
typing: strict
with_conventional_commits: true
with_typer_cli: true
